### ISSUE TITLE
but I can’t connect to the board with the test HAL. I use 5A-75E-V7.1colorlight

### ISSUE THREAD

**Issue by wuyatom** [faeboli/Lcnc#1] opened 2022-11-23 04:29 UTC
I used the firmware generated by your firmware lnc_75e_v7_30029i9s9e8p.py. I changed the IP address to test, and I can PING the board, but I can’t connect to the board with the test HAL. I use 5A-75E-V7.1colorlight, which can help Let me see what's wrong, thank you
[https://forum.linuxcnc.org/27-driver-boards/44422-colorcnc-colorlight-5a-75e-5a-75b-as-fpga-controller-board/257424?start=330](url)

**Comment by faeboli** [comment] 2022-11-23 07:16
Hi, good to know that the board at least answers to ping


1- can you change the default ip the driver is referring to in Lcnc.h line 13 and rebuild?
2- Can you try to upload the bitfile I included in the folder in the fpga?
Lcnc/prebuilt_firmwares/75e_v7_30o29i9s9e8p/Lcnc_75e_v7_30o29i9s9e8p.bit
this will have an ip of 192.168.2.50
3- Can you use wireshark to dump the packets interchange between the board and
the host pc? This will be very helpful
Also on what version of litex are you building?

Thanks
fabio

**Comment by wuyatom** [comment] 2022-11-23 15:32
Thank you, I changed the IP address of Lcnc.h according to what you taught, and now I can communicate with the board, and now there is a new problem, I don’t know whether I need to connect to the hardware to test or what, Linuxcnc presses the jog or Running the code will cause a joint following error

**Comment by faeboli** [comment] 2022-11-29 18:47
> Thank you, I changed the IP address of Lcnc.h according to what you taught, and now I can communicate with the board, and now there is a new problem, I don’t know whether I need to connect to the hardware to test or what, Linuxcnc presses the jog or Running the code will cause a joint following error

Hi, were you able to have progress with the driver? If you agree I'll close this issue since it Is not a bug, let me know!

**Closed as completed** 2022-11-29 20:59 UTC
Labels: question
